### ISSUE TITLE
Install Issue on Ubuntu 19.10

### ISSUE THREAD

**Issue by Arthurk12** [iEvgeny/cctv-viewer#1]
Sorry for using this method to contact you, but i couldn't find another.
This week I installed cctv-viewer via ubuntu desktop store but when I try to run it nothing happens.
So I tried to launch it from terminal, and this message appeared. Hope it helps in your development:

```
Qt: Session management error: None of the authentication protocols specified are supported
QQmlApplicationEngine failed to load component
qrc:/src/qml/main.qml:26 Type SingleApplicationDialog unavailable
qrc:/src/qml/SingleApplicationDialog.qml:4 module "QtQuick.Dialogs" is not installed
```

**Comment by iEvgeny** [comment]
Hi!
Thank you for the report! Fixed in the last release.
Please reinstall the application or wait for automatic update to six hours.
