### ISSUE TITLE
Does not display H265 rtsp streams

### ISSUE THREAD

**Issue by Locutu5** [iEvgeny/cctv-viewer#12]
Using Arch Linux with an xmeye dvr and rtsp streaming the following errors are shown.

[QmlAVDemuxer @ 556763384d20] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 7f12c800ab70] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 7f12c800a5c0] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 5567634575a0] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 7f12c800a740] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 7f12c800a310] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 7f12c8009ee0] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 7f12c800c480] Unable read frame: "Immediate exit requested" (-1414092869)
[QmlAVDemuxer @ 7f12c800a310] Unable read frame: "Immediate exit requested" (-1414092869)

The stream used is rtsp://192.168.1.XX:554/user=admin&password=XXXXXXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100

The dvr streams with h265 codec and the above stream URL works fine on vlc and cctv-watcher programs

**Comment by iEvgeny** [comment]
Please test the stream with FFmpeg first:
`ffplay rtsp://192.168.1.XX:554/user=admin&password=XXXXXXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100`

Then try increasing the values `-analyzeduration 0 -probesize 500000` in "AVFormat options" field (5000000 for both by default). These may not be optimal for your case.

You may also need to send me the debug output. To do this, run the CCTV Viewer as follows:
`export VERBOSE_LEVEL=3 && cctv-viewer  2>&1 | tee debug.log`

Please be careful. The output may contain sensitive data.
Use https://gist.github.com/ to post the output or email me the file.

**Comment by Locutu5** [comment]
Thanks for the reply. With the ffplay test I get the following result

fplay version n4.4 Copyright (c) 2003-2021 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
rstp://192.168.1.7:554/user=admin: Protocol not found
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
^C
[1]   Done                    ffplay rstp://192.168.1.7:554/user=admin

Further research shows that ffplay (and ffmpeg) view rstp as a demuxer and need more command line options. I tried the following

ffplay -rtsp_transport tcp -f rtsp rstp://192.168.1.XX:554/user=admin&password=XXXXXXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100

This returns
ffplay version n4.4 Copyright (c) 2003-2021 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x7f51a4000c80] method DESCRIBE failed: 401 Unauthorized0   
rstp://192.168.1.7:554/user=admin: Server returned 401 Unauthorized (authorization failed)

So I am getting somewhere. Where can I put the ffmpeg arguments in cctv-viewer?

**Comment by iEvgeny** [comment]
Oh sorry... I seem to have forgotten to add the quotes to the ffplay command.
Try it: `ffplay "rtsp://192.168.1.XX:554/user=admin&password=XXXXXXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100"`

AVFormat options are set in the sidebar in the Viewport menu.

**Comment by Locutu5** [comment]
That still returns "protocol not found" but when I use the following arguments

ffplay -rtsp_transport tcp -f rtsp "rstp://192.168.1.XX/user=admin&password=XXXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100"

I get the following error.

[rtsp @ 0x7f3fa4000c80] method DESCRIBE failed: 451 ERROR0B f=0/0   
rstp://192.168.1.XX/user=admin&password=XXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100: Server returned 4XX Client Error, but not one of 40{0,1,3,4}

**Comment by Locutu5** [comment]
ffplay now works with

ffplay -rtsp_transport tcp -f rtsp "rtsp://192.168.1.XX/user=admin&password=XXXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100"

The reason it didn't work before is that in the URL it is now rtsp. Before it was rstp (which worked in vlc)

Now I need to figure out how to get that working in cctv-viewer and we will be golden.

**Comment by Locutu5** [comment]
SOLVED!!

I now have it working in cctv-viewer. Thank you very much for your help. 

For those who have the same problem I did the following.

In the viewport setup I add (without quotes) 

rtsp://192.168.1.XX/user=admin&password=XXXXXXXXX&channel=1&stream=0.sdp?real_stream--rtp-caching=100

In the program settings in the Default AVFormat options I included  (without quotes) 

-rtsp_transport tcp -f rtsp

**Comment by iEvgeny** [comment]
Yes, you are absolutly right. If you do not take into account the typo in the protocol scheme, which I unfortunately did not notice, then for FFmpeg it is often necessary to additionally specialize the transport.
Additionally, I would like to note that the parameter `-f rtsp` refers to output and is not required in this case.

**Comment by Locutu5** [comment]
Yes, that works as well :)
