### ISSUE TITLE
Dual Screen

### ISSUE THREAD

**Issue by Billysredhat** [iEvgeny/cctv-viewer#13]
Hello
I am running CCTV-Viewer on Ubuntu and it is perfect.  I run two screens with several different cameras.  My question is when I reboot it only reloads one screen and I have to basically set the 2nd screen up from scratch again.  Is there a way for me to save and load both screens just as they were prior to a reboot?

**Comment by iEvgeny** [comment]
Hi!
I think I could implement setting the preset number on startup via the command line. Would this option be acceptable?

**Comment by iEvgeny** [comment]
So. Now you can explicitly define the preset number, full screen mode, and window coordinates when starting from the command line. It is also available to explicitly specify the location of the configuration file. Run the command `cctv-viewer -h` for reference.
Launch example for two screens with 1920x1080 resolution:
`(cctv-viewer -f -p 0  -geometry 1920x1080+0+0) & (cctv-viewer -f -p 1  -geometry 1920x1080+1920+0) &`

Additionally, you may need to enable the launch of multiple instances of the application in the settings.

**Comment by Billysredhat** [comment]
Thank you for your help I will try that.
