### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by skela** [iEvgeny/cctv-viewer#15]
Having it as a snap is awesome, but what about flatpak?

**Comment by iEvgeny** [comment]
Not planned yet. But you can use the PPA: https://launchpad.net/~ievgeny/+archive/ubuntu/cctv-viewer

**Comment by skela** [comment]
I'm an arch user, so cannot use the PPAs. Only mentioned flatpak because the only snap app I've installed on my system is cctv-viewer :D 

Keep up the awesome work though!

**Comment by iEvgeny** [comment]
For Arch, just use the AUR: https://aur.archlinux.org/packages/cctv-viewer-git/
