### ISSUE TITLE
[Feature Request] Keyboard Shortcuts

### ISSUE THREAD

**Issue by skela** [iEvgeny/cctv-viewer#16]
Would be really cool if we could change the current preset with some keyboard shortcuts, so for example: 
Alt + 1 -> Preset 1
Alt + 2 -> Preset 2

**Comment by iEvgeny** [comment]
Implemented for the first 9 presets in the latest version. Please test it.

**Comment by skela** [comment]
Wow, awesome, nice work!

I tested it with the latest version via snapcraft:
Name         Version    Rev    Tracking       Publisher   Notes
cctv-viewer  0.1.8+git  734    latest/stable  ievgeny     -
core         16-2.51.1  11316  latest/stable  canonical✓  core
core20       20210429   1026   latest/stable  canonical✓  base

Works :D Thx so much!
