### ISSUE TITLE
1 + 5 layout

### ISSUE THREAD

**Issue by ratmonkey73** [iEvgeny/cctv-viewer#17]
Is this possible? I see it in the slide on the snapcraft website, but i can't figure out how to do it. Is there a manual for CCTV Viewer?

**Comment by iEvgeny** [comment]
Of course it's possible.
You must select the cells with the mouse as shown in the screenshot and click the Merge button in the Tools menu.
![image](https://user-images.githubusercontent.com/3954130/129151871-757b5fba-23ab-4be3-bea6-c05206153778.png)

**Comment by ratmonkey73** [comment]
Perfect, thanks very much!
