### ISSUE TITLE
No audio in CCTV-Viewer.

### ISSUE THREAD

**Issue by ironwolf269** [iEvgeny/cctv-viewer#20]
I have 3 rtsp cameras and I can't get audio from any of them while in the program. I am using the ppa version btw.
This is what it says when I run it through terminal:

User@pop-os:~$ cctv-viewer
QML debugging is enabled. Only use this in a safe environment.
using null output device, none available
using null output device, none available
using null output device, none available

Is this something I can fix? Or is it a bug?

Edit:
I fixed it my self by installing libqt5multimedia5-plugins.

**Comment by iEvgeny** [comment]
Hi!
Thanks for the bug report. Fixed in commit 3c656da.
