### ISSUE TITLE
Install snap problem - Filesystem uses "lzo" compression in Jetson Nano

### ISSUE THREAD

**Issue by zedmaster** [iEvgeny/cctv-viewer#21]
Hi,

First of all, thank you for developing this software. It's the only one that works perfectly on my Linux.

But unfortunately, I am unable to install via SNAP due to the error below. I looked for everything and I can't find how to solve this problem.

Can someone tell me a way to install CCTV View by snap or compile by hand.

I've tried using Ubuntu 20.04 and NVIDIA's custom Debian but both have the same error.

```
dec 29 03:29:09 nano systemd[1]: snap-cctv\x2dviewer-803.mount: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit snap-cctv\x2dviewer-803.mount has entered the 'failed' state with result 'exit-code'.
dec 29 03:29:09 nano kernel: squashfs: SQUASHFS error: Filesystem uses "lzo" compression. This is not supported
dec 29 03:29:09 nano systemd[1]: Failed to mount Mount unit for cctv-viewer, revision 803.
-- Subject: A start job for unit snap-cctv\x2dviewer-803.mount has failed

```

Thanks in advance.

**Comment by iEvgeny** [comment]
Hi!
It looks like there is no support for LZO compression in the kernel, which is very strange for Ubuntu.
As a workaround, I suggest using my PPA: https://launchpad.net/~ievgeny/+archive/ubuntu/cctv-viewer
