### ISSUE TITLE
ignoring -f mjpeg option?

### ISSUE THREAD

**Issue by frgazor** [iEvgeny/cctv-viewer#23]
I'm trying to use esp32-cam and it works if open it like this: ffplay -f mjpeg http://192.168.2.178:81/stream. Without -f mjpeg parameter I get an **Invalid data found when processing input** error.

However when I try to use it with cctv-viewer it doesn't work even if I set -f mjpeg in AVFormat options. **Invalid data found when processing input error** is displayed every few seconds in the console.

I have another esp32-cam with different firmware and that one works without a problem. Doesn't even need -f mjpeg parameter.

**Comment by iEvgeny** [comment]
The "-f" (Force format) option belongs to the group of "General" or "Main" options, not "AVOptions". See `ffplay --help`.
Your situation indicates that ffmpeg cannot automatically detect the format of the stream from one of the cameras. Try increasing the AVFormat "-analyzeduration" "-probesize" options and test it on ffplay.
In general, it will not be difficult to implement support for the "-f" option.

**Comment by frgazor** [comment]
Thank you for your response

I have already tried all possible values for "-analyzeduration" and "-probesize", even crazy large values but no luck. I just have to force the format with this one. My other cameras (xiaomi modified for rtsp support, generic foscam and another esp32) all work without a glitch.

**Comment by iEvgeny** [comment]
I added support for "-f" option for AVFormat options field. Please try it.

P.S.
If you are using a PPA, please also note that building for older distributives is not supported.

**Comment by frgazor** [comment]
I built the new version from source and it works! Thanks a lot!
