### ISSUE TITLE
Cant compile on arch linux.

### ISSUE THREAD

**Issue by kellerman** [iEvgeny/cctv-viewer#24]
Hello.
Using aur package
https://aur.archlinux.org/packages/cctv-viewer-git
When compiling, this error shows:
```
CMake Error at CMakeLists.txt:114 (qt5_create_translation):
  Unknown CMake command "qt5_create_translation".
```
Am I missing any dependencies?

**Comment by kellerman** [comment]
Hello, @iEvgeny 
Thanks for your response.

**Comment by infra223** [comment]
Hi kellerman,

I am unable to reproduce the error from a fresh Arch Linux install.
You can try a full system update and try again:
   sudo pacman -Syyu

If that does not work please provide more info on your setup:  
Are you on x86 or ARM?
Are you running Arch proper or derivative like Manjaro?
Anything else unique to your setup that might be noteworthy?

**Comment by kellerman** [comment]
Hello, @infra223 .
I also tried on a fresh install not long ago. Also tried on two arch x86_64 machines running fully updated Arch.
First it failed and I had to install:
- qt6-quick3d
- qt6-tools
- qt6-multimedia
- qt6-translations

After doing that, it now fails like this:

`-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib/libxkbcommon.so (found suitable version "1.4.0", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
CMake Error at CMakeLists.txt:114 (qt5_create_translation):
  Unknown CMake command "qt5_create_translation".
`
Seems it might be a missing dependency then?

**Comment by infra223** [comment]
Hi @kellerman 

The project does not have any qt6 dependencies, @iEvgeny  can correct me if I am wrong.

Please check if the qt5-translations package is installed:  
> pacman -S qt5-translations

**Comment by kellerman** [comment]
Hi @infra223 
Package qt5-translations is installed. Without installing the qt6 packages there are errors like this:

> CMake Error at CMakeLists.txt:66 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "LinguistTools".

  Expected Config file at
  "/usr/lib64/cmake/Qt6LinguistTools/Qt6LinguistToolsConfig.cmake" does NOT
  exist

**Comment by infra223** [comment]
@kellerman 

I've now explicitly included the following dependencies in the build package that are optional for the qt5-base package but required for cctv-viewer:
- qt5-translations  
- qt5-svg 

Do a clean install from AUR (presuming you using yay):
`yay -S cctv-viewer --rebuild --redownload --answerclean Y`

or do a fresh clone form AUR and makepkg if you do not use an AUR helper.


I do not know how Qt6 fits into the picture here.  All dependencies are for Qt5.  
@iEvgeny  any thoughts on Qt6?  

@kellerman  did you perhaps  make any symlinks to redirect the references for Qt5 libraries to the Qt6 libraries?

**Comment by kellerman** [comment]
@infra223 
```
==> Starting build()...
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib/libxkbcommon.so (found suitable version "1.4.0", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
-- Could NOT find Qt6LinguistTools (missing: Qt6LinguistTools_DIR)
CMake Error at CMakeLists.txt:66 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "LinguistTools".

  Expected Config file at
  "/usr/lib64/cmake/Qt6LinguistTools/Qt6LinguistToolsConfig.cmake" does NOT
  exist

  



-- Configuring incomplete, errors occurred!

```
OK. Removing all qt6-* packages did the trick. I had qt6-* required by qbittorrent. It compiled fine. I'll just reinstall qbittorrent after compiling cctv-viewer.

**Comment by iEvgeny** [comment]
Hi @kellerman!
Build with Qt6 is currently not supported.  I plan to work on this, but it's quite a large amount of time.
If I understand correctly, this issue can be closed?

**Comment by infra223** [comment]
Thanks @kellerman,

I will install qbittorrent with the Qt6 dependencies on a VM when I have some time and play around with it.  I just find it strange that it tries to use the Qt6 packages instead of Qt5.  

Ill let you know what I find.

**Comment by parkerlreed** [comment]
So there's no way to build this with qt6 present? I am unable to remove qt6 from my system.

**Comment by parkerlreed** [comment]
Or maybe it's working? 

I'm seeing this (file doesn't exist)

```
make[1]: *** No rule to make target 'translations/cctv-viewer_ru_RU.qm', needed by 'release/qrc_cctv-viewer.cpp'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/deck/build/cctv-viewer'
make: *** [Makefile:42: release] Error 2
```
