### ISSUE TITLE
Camera lag overtime

### ISSUE THREAD

**Issue by bswaby** [iEvgeny/cctv-viewer#25]
Love the software so far.  The only thing we are finding is that we seem to gain about 1 second of lag each day.  Right now we have a cron job to just restart the computer each morning, but would rather not have to do that.

**Comment by iEvgeny** [comment]
In my case, everything works 24x7 for weeks or even months without lag accumulation. I can only assume that your machine's resources are exhausted.
CCTV Viewer has peculiarities related to transferring frames between threads. It does not yet know how to discard them if we do not have time to play them back. In this case we should also see a gradual increase in memory usage.

**Comment by iEvgeny** [comment]
If this is still relevant for you, version 0.1.9-alpha has deeply refactoring the built-in player.
Many improvements have been made and in particular the frame queue length limit I mentioned above. I don't think it's the frame queue, but maybe your problem will be solved by an overall improvement in code quality.
Also in experimental mode, hardware acceleration of video decoding is available: #9
