### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by Billysredhat** [iEvgeny/cctv-viewer#26]
Is there a way to disable the drop down menus after I configure the streams? I am using an unattended device to display cameras and would like to prevent someone from changing the settings and mostly viewing my username and password in the Viewport field.

**Comment by iEvgeny** [comment]
I did the initial implementation of "kiosk mode". To use this mode, use the -k or --kiosk command line options.

P.S.
Please note. Passwords are still stored in plain text in the configuration file.

**Comment by iEvgeny** [comment]
Yep. If you use PPA:
`sudo apt update && sudo apt dist-upgrade`
Or if you use Snap, please, wait 6 hours for automatically update or reinstall  the application.

**Comment by Billysredhat** [comment]
Perfect, Thank You very much for your work and help.
