### ISSUE TITLE
Feature request: use Delete button in keyboard to delete one or multiple video streams

### ISSUE THREAD

**Issue by RadhiFadlillah** [iEvgeny/cctv-viewer#28]
Right now, as far as I know, the only way to remove a video stream is by setting its URL to empty. Thanks to this, it's quite cumbersome to delete multiple video streams since we have to remove its URL one by one.

To solve this issue, it would be nice if the "Delete" button in keyboard could be used to remove video streams from all of the selected players.

Thanks!

**Comment by iEvgeny** [comment]
Implemented in the latest release. Please test it.

**Comment by RadhiFadlillah** [comment]
Yes, it works now. Thanks!
