### ISSUE TITLE
Feature request: add text field in sidebar to specify custom grid size

### ISSUE THREAD

**Issue by RadhiFadlillah** [iEvgeny/cctv-viewer#29]
Right now, in sidebar there are only 1x1 to 4x4 grid size options. However, after changing the configuration manually, apparently `cctv-viewer` can handle custom grid size like 4x3.

With that said, since it already supports custom grid size, could you add text fields in sidebar to input custom grid size? This way, user can easily specify custom size without manually editing the config file.

Thanks!

**Comment by iEvgeny** [comment]
Custom grid size is supported initially. Please click and hold on any window division button to set a custom grid size.

**Comment by RadhiFadlillah** [comment]
Oh my, sorry for missing it. Thanks!
