### ISSUE TITLE
How to add cameras

### ISSUE THREAD

**Issue by arrowgroupinc** [iEvgeny/cctv-viewer#31]
Ok, I'm obviously missing something here. I have installed cctv-viewer and have it running. I see the 2 demo cameras. Now, how do I add my own cameras and remove the demos? 

I've looked all over the place but can not see any way to config this with my own cameras.

**Comment by iEvgeny** [comment]
CCTV works with streams, not cameras. In the "Viewport" section of the sidebar, you can add a stream for your camera, as well as make other settings.
As an example, the stream for Hikvision cameras: `rtsp://admin:12345@192.168.200.11:554/ISAPI/Streaming/Channels/101`
