### ISSUE TITLE
Feature request: Support audio for focused stream

### ISSUE THREAD

**Issue by MindrustUK** [iEvgeny/cctv-viewer#32]
Would it be possible to add audio support for the "focused" stream. Example if I have 9 cameras in a 3x3 grid and I full screen one of the streams, could cctv-viewer also render the audio (if the camera supports the option)?

I've tested playing a camera via mplayer and audio works on the primary stream so I'm hoping this won't be too much trouble to add.

**Comment by iEvgeny** [comment]
If I understand you correctly, do you want to automatically "unmute" sound for a viewport that is in full screen mode (double-click or the F key)?

**Comment by MindrustUK** [comment]
Yes, that's correct.

**Comment by iEvgeny** [comment]
Implemented in the last commit. Please test it.

**Comment by MindrustUK** [comment]
Awesome, tested and working great! Thanks for your work as always.
