### ISSUE TITLE
Cannot enter stream URL with parameters

### ISSUE THREAD

**Issue by jdarmst** [iEvgeny/cctv-viewer#35]
Dahua DVRs follow the pattern as follows:

https://[USER]:[PASSWORD]@[IP]:[PORT]/cam/realmonitor?channel=[NUMBER]&subtype=[STREAM]

the parameters at the end do not seem to work with this software.

**Comment by Billysredhat** [comment]
I have numerous Dahau cameras running in this software using the following stream url:


rtsp://user:password@IP/cam/realmonitor?channel=1&subtype=1

**Comment by iEvgeny** [comment]
In any cases where you cannot play a stream in the CCTV Viewer, I recommend using ffplay to check if the URL is correct.

**Comment by Dejavou42** [comment]
The fix for me with dahua cameras is to add "rtp_transport tcp" to avformat options. Hope that fixes yours too.
