### ISSUE TITLE
Feature Request: Auto Scan Presets with dwell time

### ISSUE THREAD

**Issue by Dejavou42** [iEvgeny/cctv-viewer#39]
It would be awesome to add a scan feature that rotates through selected presets and allows a custom dwell time. Also, a keyboard shortcut to switch between presets / dragging on touch screen would be great.

I.e. Preset 1 displays for 60 seconds, preset 2 displays for 30 seconds, preset 5 displays for 90 seconds.

the GUI would have to be reorganized a bit to accomplish this, but I may dig into the code a little to see if I can find a solution / test.

**Comment by iEvgeny** [comment]
Just try Alt+1, Alt+2, ..., Alt+9

**Comment by Dejavou42** [comment]
That works for the keyboard shortcut! Thank You

**Comment by wiryonolau** [comment]
Any console command to change preset ? Should be able to run this with cron

**Comment by iEvgeny** [comment]
Only with application restart. Use the -p option.
`cctv-viewer --help` for details

**Comment by KaKi87** [comment]
What if I have more than 9 presets ?

**Comment by iEvgeny** [comment]
> What if I have more than 9 presets ?

Use "Alt+Right", "Alt+Right" shortcuts. This feature will be available within 24 hours on the desktop release.

**Comment by KaKi87** [comment]
Nice.
What about the other shortcuts that I requested in #52 ?
Thanks

**Comment by iEvgeny** [comment]
Replied in corresponding thread
