### ISSUE TITLE
Feature request: configuration button / menu direction.

### ISSUE THREAD

**Issue by MindrustUK** [iEvgeny/cctv-viewer#4]
The user interface doesn't appear to be intuitive (the menu being hidden on the right).

Reading the comments (before looking at the source code) on the Ubuntu store I found the menu. I also found many others complaining of the same issue.

Could you add a button, indicator, or other option somewhere either in the main window or drop down menu to pop this option out? This should make it obvious for any users who don't take time to read and understand. Thanks.

**Comment by iEvgeny** [comment]
Well... I allowed myself to rethink the concept of the sidebar.
It seems to me now more intuitive. Also, the new concept provides more opportunities to extend functionality.
What will be your user experience with the new menu?

**Comment by MindrustUK** [comment]
This is REALLY friendly. I don't think anyone should have an issue using this now. Great work, thanks!
