### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by n9tax** [iEvgeny/cctv-viewer#41]
This program has a major memory leak. Starts running 14 cameras with about a half gig memory usage. Within 24 hours fills the 16gig on the computer and crashes out. Pretty bad for what this is supposed to be. Other than that its a pretty amazing program.

**Comment by n9tax** [comment]
This is a bare metal install of Ubuntu 22.04 on an HP Elitedesk by the way.

**Comment by Billysredhat** [comment]
Not sure exactly why you're having such a large memory issue, but I just want to say this program is awesome. Hopefully the developer can give you some help on your issue, but I have around 25 computers at different locations running this software. Each computer using 2 monitors, via 2 hdmi outputs, with 9 cameras per screen for a total of 18 cameras per computer. They run virtually 24/7 and get rebooted once a month. The memory usage stays consistent between reboots. I have not had any issues with CCTV-Viewer and it's been in use for almost a year.

**Comment by n9tax** [comment]
Strange did you install from source or use the snap? Maybe that is the issue.

**Comment by AnchorHRG** [comment]
I am also experiencing the memory leak issue. 16G RAM, fills up completely in about 1.5hrs causing the program to crash.
I'm using the snap on Linux Mint Debian Edition.

**Comment by n9tax** [comment]
So I know what the issue is. From another issue comment I found this. And speed of the system and whether it can run all of the frames collected is why some have no issues and others have varying degrees of issue. I may have some time to peek at the source one of these days.

Quote from the author "In my case, everything works 24x7 for weeks or even months without lag accumulation. I can only assume that your machine's resources are exhausted.
CCTV Viewer has peculiarities related to transferring frames between threads. It does not yet know how to discard them if we do not have time to play them back. In this case we should also see a gradual increase in memory usage."

**Comment by iEvgeny** [comment]
In version 0.1.9-alpha, deep refactoring of the code has been performed, including for memory leaks.
A number of other improvements are also available, including hardware accelerated video decoding: #25 #9
The Qt GUI still needs to be optimized for memory usage, but most of the work is done. Please test it.

**Comment by n9tax** [comment]
Ok I am running the alpha now. I will let you know of the performance changes.

**Comment by n9tax** [comment]
It is much more stable now. Runs for weeks only froze up one time and I cannot reproduce that so may be unrelated. Amazing work
