### ISSUE TITLE
Cannot run app with X server

### ISSUE THREAD

**Issue by qarmin** [iEvgeny/cctv-viewer#42]
After changing graphic card from Nvidia to AMD, Gnome automatically changed default server from x to wayland.
Next I reverted change, but still looks that app want to run with wayland but my windowsing system is now x11
```
Failed to create wl_display (Connection refused)
Using Wayland-EGL
failed to initialize EGL display
qt.qpa.plugin: Could not load the Qt platform plugin "wayland-egl" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```

**Comment by iEvgeny** [comment]
CCTV Viewer should work fine with both X11 and Wayland. Try installing CCTV Viewer from the PPA first: https://launchpad.net/~ievgeny/+archive/ubuntu/cctv-viewer
