### ISSUE TITLE
How to stream with complicated auth?

### ISSUE THREAD

**Issue by parkerlreed** [iEvgeny/cctv-viewer#44]
I currently have a script that sets up and pipes a stream to stdout.

Is there a way to use this within cctv viewer?

```
#!/bin/bash
curl -k -u 'user:pass' --ignore-content-length "https://192.168.100.59:19443/https/stream/mixed?video=H264&audio=G711" --output -
```

**Comment by parkerlreed** [comment]
I tried formatting as a URL which works for ffplay/ffmpeg but not within cctv-viewer

```
https://user@email.com:longpassword@192.168.100.59:19443/https/stream/mixed?video=H264&audio=G711
```

Doesn't print anything to stdout which would lead to knowing why it's not working.

**Comment by parkerlreed** [comment]
Ok so apparently it doesn't... ffplay thinks the H264 is MJPEG and just keeps trying to process (which is what cctv-viewer may be doing because it's not printing any errors)

```
[mpjpeg @ 0x7f7be8000c80] Expected boundary '--' not found, instead found a line of 98 bytes
[mpjpeg @ 0x7f7be8000c80] Expected boundary '--' not found, instead found a line of 64 bytes
[mpjpeg @ 0x7f7be8000c80] Expected boundary '--' not found, instead found a line of 42 bytes
[mpjpeg @ 0x7f7be8000c80] Expected boundary '--' not found, instead found a line of 127 bytes
```
It works passing the same URL to mpv which uses ffmpeg.

**Comment by parkerlreed** [comment]
ffplay starts working with `-f h264`

Does not work in cctv-viewer when adding to the parameters

```
-f h264 -probesize 500000 -analyzeduration 0
```

**Comment by iEvgeny** [comment]
What is the console output of CCTV Viewer with the given parameters?
Have you tried setting the default values for probesize and analyzeduration (5000000)?

**Comment by parkerlreed** [comment]
Sadly there's no output with or without the `-f 264` with the correct URL in place.

From what I've observed, I believe the -f h264 is getting ignored, and the stream is "working" with the incorrect assumption that it's MJPEG (Just like raw ffplay behavior)

Since it's "streaming" butwith the incorrect format, nothing is being printed to stdout. 

ffplay with the same parameters 

![image](https://user-images.githubusercontent.com/841440/210105645-5585287e-347e-4a43-a729-18b672f81d74.png)

cctv-viewer (Note it doesn't print invalid to the preview pane so I think it thinks it's working)

![image](https://user-images.githubusercontent.com/841440/210105758-bde6a614-aa72-4105-861c-21dad4e2d9bf.png)

**Comment by iEvgeny** [comment]
Try the following debugging method: `export VERBOSE_LEVEL=3 && cctv-viewer  2>&1 | tee debug.log`
The output will be voluminous, so the best way to publish it is https://gist.github.com.
Also, let me clarify if the demo streams that are set by default when installing the application are played?

**Comment by parkerlreed** [comment]
Yes the demos work fine and I have other cameras that load fine.

I will give that a test and report back, thank you!
