### ISSUE TITLE
Launch on Startup

### ISSUE THREAD

**Issue by 1Aw3someAlex** [iEvgeny/cctv-viewer#45]
Any plans for a "Launch on Startup" setting? 

Looked at a few guides online and none of them work.

**Comment by iEvgeny** [comment]
If you mean launching CCTV Viewer at the start of the operating system, then on Linux systems it is considered good practice to do this by DE or OS.

**Comment by Billysredhat** [comment]
I have several Linux computers running CCTV-Viewer they all star at startup. It's like a 2 line script that runs at startup.

**Comment by iEvgeny** [comment]
This is one of the right approaches to solving the task.
Maybe you can use additional parameters to control the CCTV Viewer more flexibly at startup: `cctv-viewer --help`

**Comment by 1Aw3someAlex** [comment]
Awesome. What two lines of script is it?

**Comment by iEvgeny** [comment]
For example in KDE, this can be done through the OC settings. In your case, you can contact your distribution's specialized community for support.

**Comment by 1Aw3someAlex** [comment]
> For example in KDE, this can be done through the OS settings. In your case, you can contact your distribution's specialized community for support.

I'm not finding any documentation on other forums so far. That's why I reached out here in the first place. I'm just using a Pi4 running rasbian (bullseye).

**Comment by 1Aw3someAlex** [comment]
> I have several Linux computers running CCTV-Viewer they all start CCTV at startup. It's like a 2 line script that runs at startup.

I'd love to get that script from you. I've been messing with this for two days now. Granted I'm not a linux guy normally. So, if you can share that, then that would be awesome.

**Comment by iEvgeny** [comment]
How to on the official Raspberry Pi forum: https://forums.raspberrypi.com/viewtopic.php?t=294014

**Comment by 1Aw3someAlex** [comment]
> How to on the official Raspberry Pi forum: https://forums.raspberrypi.com/viewtopic.php?t=294014

yeah, none of those worked for me. I ended up making a shell script to and made a service to run that shell script. 
However, I've noticed that when I just put 'cctv-viewer' into the CLI, it will open, but the CLI reports the following back to me:

root@raspberrypi:~# cctv-viewer
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory

**Comment by iEvgeny** [comment]
If everything works fine, just ignore it. This is probably some kind of problem with the Snap package environment variables specific to your distribution.
