### ISSUE TITLE
Feature Request: Stand-alone executable

### ISSUE THREAD

**Issue by rmccormi** [iEvgeny/cctv-viewer#46]
Forgive my ignorance, I am new to github, and a novice at programming.  Is it possible to compile this application as a stand-alone executable?  I wish to bundle it into a 'kiosk' package, which is based on Gentoo Linux, but does not include SNAP.

**Comment by Billysredhat** [comment]
You can use the PPA I don't use SNAP at all.

**Comment by rmccormi** [comment]
Thanks, but I haven't run across instructions on how to to add the PPA. All I find is the SNAP installer, or this source code on GitHub.  At any rate, I need all dependencies included to work with the Kiosk platform.

**Comment by Billysredhat** [comment]
I can post the PPA this evening  when I get home if that helps.

**Comment by rmccormi** [comment]
That would be wonderful, thanks!

**Comment by Billysredhat** [comment]
The ppa is: 

ppa:ievgeny/cctv-viewer

**Comment by iEvgeny** [comment]
The link to the PPA is right in the README.TXT file on the main page of the repository. In the file https://github.com/iEvgeny/cctv-viewer/blob/master/debian/control you can find build and runtime dependencies for Debian-based systems. Basically you need GCC, CMake, Qt5 and some libraries of FFmpeg. In theory, it should work in any modern Linux distribution.

**Comment by rmccormi** [comment]
Thanks, Evgeny. I completely overlooked that one of those 'buttons' was a link to the PPA.

**Comment by rmccormi** [comment]
Thanks to Billysredhat, as well!
