### ISSUE TITLE
manual compile instructions (for x32)?

### ISSUE THREAD

**Issue by dm8mydog** [iEvgeny/cctv-viewer#48]
Could you please provide instruction of how to manually compile the source for x32.

I haven't done any of that in a long while and I need some handholding.

**Comment by dm8mydog** [comment]
Apologies for wasting more of your time.

For starters this bit might help anyone else reaching here via google:
Since the host machine is really ancient and it can't run 64bit I'm stuck with ubuntu 18.04x which tops up by default at qt5.9.0 , which is not high enough. The process ended with asking for a minimum of qt5.12x.
So, by following roughly the instructions here: 

> https://stackoverflow.com/questions/63993379/how-to-upgrade-the-qt-version-through-the-command-line

and partly from here:

> https://medium.com/@lyl1617670866/how-to-install-and-configure-qt5-manually-on-ubuntu-18-04-8e27edcdf7a

(note the opt path for the install is different from what you got by the ppa:beineri/opt-qt-5.14.0-bionic ...  so adjust accordingly)

To confirm success:

> $ qmake --version
> QMake version 3.1
> Using Qt version 5.14.0 in /opt/qt514/lib

So far so good, and now qmake completes successfully with no warnings!

Yay... now I get this error message when I do make -j4:

> make[1]: *** No rule to make target 'translations/cctv-viewer_ru_RU.qm', needed by 'release/qrc_cctv-viewer.cpp'.  Stop.
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/home/mini/cctv-viewer'
> Makefile:42: recipe for target 'release' failed
> make: *** [release] Error 2

Help, please?

**Comment by iEvgeny** [comment]
Use `lrelease *.pro` in the project directory to build translations before `make`. Or just use cmake instead of qmake, then the translations will be built automatically.

P.S.
If you use Qt from /opt, you will need to distribute the corresponding libraries with the application to be able to run it.

**Comment by dm8mydog** [comment]
Success!
thank you
