### ISSUE TITLE
Change grid and geometry needed

### ISSUE THREAD

**Issue by semo163** [iEvgeny/cctv-viewer#5]
Hello Evgen.
Thank you for your good work!
At long last found easy solution for exactly what I need - sending rtsp flow from several IP cams to one video surveillance wall without any web servers proxies and so on and so forth !
So actually for complete  happiness i need just one minor thing: possibility to change grid. Instead of pre build 1, 2x2, 3x3, 4x4 grid layout make it 3x2 4x2 something like that (in accordance with amount of cams). I managed to change layout itself in CCTV viewer.conf file and grid is ok, but now cams does not fit all display geometry... There is big black space under the cams grid and beneath. As if screen geometry in 3x2 grid can not be calculated right, by the program. Cams actually could occupy more available space on screen. Is it possible to make some change in the program to make cameras occupy as much free monitor space as possible ? Thanks.

**Comment by iEvgeny** [comment]
Hi!
The possibility of changing preset grid sizes is already implemented. You do not need to edit the configuration file for this purpose.
On the right Side Bar in the "Windows division" group make a long tap (click) on the desired button. As a result, you will have access to editing grid aspect ratios for the current preset.
![image](https://user-images.githubusercontent.com/3954130/93514217-99f57180-f92f-11ea-861f-eb0d8b24922d.png)

**Comment by semo163** [comment]
Evgen great respect.
Thank you for quick response and pointing to this great feature. 
99% of what I need !
One percent is to make 6 cameras to occupy all available screen size (or as much as possible of it). Current screen dimention is 380mm x 300mm.
![gscreenshot_2020-09-17-234015](https://user-images.githubusercontent.com/49680557/93519330-2b201480-f93f-11ea-84fa-a00529b7bd48.png)
Tomorrow will try on 80'' LCD. Will see how it's going to look like and how much free space will not be occupied.
Thanks.

**Comment by iEvgeny** [comment]
At the moment, two main aspect ratios of 16:9 and 4:3 are supported. You can make the respective settings in the section "Geometry". Experiment with pressing the desired button again. This will bring the total window size to the selected proportions.
If we are talking about full screen mode, then in your case you will not reach 100% filling the available area. This is because the frame in each cell will always keep the original aspect ratio. Stretching is not supported.
If your goal is to place six 4:3 cameras in a 4:3 display no matter what, then I would suggest this option:
![image](https://user-images.githubusercontent.com/3954130/93524659-805b2680-f93d-11ea-98ce-16d54f19e714.png)

**Comment by semo163** [comment]
Hello Evgen.
Another problem recently emerged... 
After I added new ip cam of another manufacturer (Hikvision DS-I102 added, another cams what are working are Misecu XM530 - if it matters) I can not see stream from this particular camera and got message in console:
[rtsp @ 0x7fad70004f00] method PAUSE failed: 551 Option not supported
[rtsp @ 0x7fad70004f00] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[rtsp @ 0x7fad70004f00] UDP timeout, retrying with TCP
[rtsp @ 0x7fad70004f00] method PAUSE failed: 551 Option not supported
[55b2d64955d0, rtsp://adminuser:adminpass@ip:port/ISAPI/Streaming/Channels/101] Unable read frame: "Операция не позволена" (-1)
[rtsp @ 0x7fadac003ec0] max delay reached. need to consume packet
[rtsp @ 0x7fadac003ec0] RTP: missed 1 packets
[h264 @ 0x7fadac069d60] Increasing reorder buffer to 1
Tried both variants (snap version and after complite uninstallation of snap CCTV_viewer installed local version from your PPA as in neighbor thread earlier) on lubuntu18.04 x64 with last upgrade and all restricted extras installed. Hikvision cam does not work.
On Arch Linux with all updates all cameras are working well.
Checked Hikvision camera rtsp settings - where are 2 options about rtsp: 1 - block unauthorized access enabled and 2 - this option is disabled. Tried both - same results. Arch is working Ubuntu does not. 
Do I need to send complete (debug) log ?

**Comment by iEvgeny** [comment]
Hi!
It is good practice in this case to use FFmpeg to inspect the stream. As example: `ffplay -analyzeduration 0 -probesize 500000 rtsp://adminuser:adminpass@ip:port/ISAPI/Streaming/Channels/101`
Also pay attention to the AVFormat options field in the settings for each viewport. FFmpeg format options are by default set to: `-analyzeduration 0 -probesize 500000` These values may need to be corrected (default values for FFmpeg `-analyzeduration 5000000 -probesize 5000000`).
You can enable CCTV Viewer debug mode like this: `export VERBOSE_LEVEL=3 && cctv-viewer`
But I suppose the output of FFmpeg should be enough in this case.

**Comment by semo163** [comment]
Thank you for very fast response !
Did as you advice to do.
Tried with different -analyzeduration and -probesize params
Got this in console:
ffplay -analyzeduration 5000 -probesize 500000 rtsp://remote:1234qwER@83.69.178.36:5448/ISAPI/Streaming/Channels/101
ffplay version 3.4.8-0ubuntu0.2 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0

**Comment by iEvgeny** [comment]
As you can see, this is not a problem with CCTV Viewer. Try this: `ffprobe rtsp://user:pass@ip:port/ISAPI/Streaming/Channels/101`
So far, we only see that the stream is not playing...

**Comment by semo163** [comment]
Sorry sorry
Was my mistake. Wrong port number.... 
Now is correct:
ffplay -analyzeduration 0 -probesize 500000 rtsp://user:pass@ip:port/ISAPI/Streaming/Channels/101
ffplay version 3.4.8-0ubuntu0.2 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
[rtsp @ 0x7fe658000b80] UDP timeout, retrying with TCP   0B f=0/0   
[rtsp @ 0x7fe658000b80] method PAUSE failed: 551 Option not supported
[rtsp @ 0x7fe658000b80] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://remote:1234qwER@83.69.178.36:5548/ISAPI/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
[rtsp @ 0x7fe658000b80] UDP timeout, retrying with TCP   0B f=0/0   
[rtsp @ 0x7fe658000b80] method PAUSE failed: 551 Option not supported
[rtsp @ 0x7fe658000b80] UDP timeout, retrying with TCP   0B f=0/0   
[rtsp @ 0x7fe658000b80] method PAUSE failed: 551 Option not supported
[rtsp @ 0x7fe658000b80] UDP timeout, retrying with TCP   0B f=0/0

**Comment by semo163** [comment]
Output from ffprobe:
ffprobe rtsp://user:pass@ip:port/ISAPI/Streaming/Channels/101
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[rtsp @ 0x5584e12b3fc0] UDP timeout, retrying with TCP
[rtsp @ 0x5584e12b3fc0] method PAUSE failed: 551 Option not supported
[rtsp @ 0x5584e12b3fc0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://remote:1234qwER@83.69.178.36:5548/ISAPI/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc

**Comment by iEvgeny** [comment]
Please pay more attention to the sensitive data in the FFmpeg output!
When playing an RTSP stream outside the subnet of an IP camera or DVR, use the TCP protocol instead of the default UDP. For this you need to use `-rtsp_transport tcp` option for FFmpeg in the cmd line and for CCTV Viewer in the "AVFormat options" field.

**Comment by semo163** [comment]
Thank for editing : -)
will try with TCP...
From arch linux 
ffprobe rtsp://user:pass@ip:port/ISAPI/Streaming/Channels/101
ffprobe version n4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://user:pass@ip:port/ISAPI/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.160000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 25 tbr, 90k tbn, 180k tbc

**Comment by iEvgeny** [comment]
Now you can play your stream like this: `ffplay -analyzeduration 0 -probesize 500000 -rtsp_transport tcp rtsp://user:pass@ip:port/ISAPI/Streaming/Channels/101`

**Comment by semo163** [comment]
Уррра Урра !!!!
Evgen you are my hero !!!
It's working now.
How can I send you a beer MAN ?

**Comment by iEvgeny** [comment]
Don't worry man!
This application was created for internal needs. If this is useful to someone, then it's already not bad)

**Comment by semo163** [comment]
Thank you very much Evgen!!!
I wish I have your contacts to send some gift !

**Comment by iEvgeny** [comment]
My e-mail is available in the profile.
I guess this issue can be closed?
