### ISSUE TITLE
Type error in snap package

### ISSUE THREAD

**Issue by qarmin** [iEvgeny/cctv-viewer#59]
```
qrc:/src/ViewportsLayout.qml:109: TypeError: Type error
```
https://github.com/iEvgeny/cctv-viewer/blob/d7543f51c0b92d5c6292687794cda4f49c337144/src/ViewportsLayout.qml#L109

**Comment by iEvgeny** [comment]
Need more info.
Your distribution, under what conditions this error occurs. Do you see the demo streams immediately after installation with the default configuration?

**Comment by qarmin** [comment]
Ubuntu 23.04 - CCTV Viewer 0.1.8-alpha

After reinstalling snap package, in demo streams, changing "Window division" to 3x3 and then to 2x2 cause to show this error

**Comment by iEvgeny** [comment]
Fix in f24ea2a
Thanks!
