### ISSUE TITLE
RTSP stream error

### ISSUE THREAD

**Issue by dcung** [iEvgeny/cctv-viewer#60]
Hi,
Thank you for the software.

I installed cctv-viewer on Debian 11 (Bullseye).

The demo stream works okay.
I tried to configure video stream from an IP camera (RTSP).
rtsp://user:password@x.x.x.x:554/ch1/1

The video was displayed for a few seconds.
It then displays 'End Media' and after that 'Invalid Media'

I can use VLC to display the video stream to confirm the video is received.

Any suggestions what I should look for and change?

Thank you.

**Comment by iEvgeny** [comment]
Hi!
First, try adding the `-rtsp_transport tcp` option to the AVFormat options field for this RTSP stream.
Also you can use ffplay as reference instead of VLC. Because CCTV Viewer is based on ffmpeg and this utility has extensive diagnostic output to the console.

**Comment by dcung** [comment]
Adding `rtsp_transport tcp` to cctv-viewer option made no difference.

I am able to display the stream with

`ffplay -rtsp_transport tcp rtsp://user:password@x.x.x.x:554/ch1/1 -x 640 -y 480`

**Comment by dcung** [comment]
Where is the config file?

I found 
`/root/snap/cctv-viewer/1037/.config/CCTV Viewer/CCTV Viewer.conf
`
but I don't see my IP cameras setting/address.

**Comment by iEvgeny** [comment]
For others who are looking for information on the configuration file location for a Snap package: `~/snap/cctv-viewer/current/.config/CCTV Viewer/CCTV Viewer.conf`
