### ISSUE TITLE
[SUGGESTION] AVX/AVX2/AVX-512 optimizations ?

### ISSUE THREAD

**Issue by forart** [iEvgeny/cctv-viewer#62]
Hi there,
since we don't have any embedded dev, we honestly don't know if this is a technically correct suggestion...
...anyway we found some interesting resources about it:

1. [Improving the compute performance of video processing software using AVX (Advanced Vector Extensions) instructions](https://www.intel.com/content/dam/develop/external/us/en/documents/41302-avxonvideoprocessing-184839.pdf)
2. [[VIMEO] Optimizing for AVX2](https://medium.com/vimeo-engineering-blog/optimizing-for-avx2-3b462ab77837)
3. [SIMD Acceleration for HEVC Decoding](https://api-depositonce.tu-berlin.de/server/api/core/bitstreams/a63541f9-c868-4305-91f3-02e8f5758f08/content)
4. [Accelerating x265 with Intel® Advanced Vector Extensions 512](https://www.intel.com/content/dam/develop/external/us/en/documents/mcw-intel-x265-avx512.pdf)
5. [Intel AVX-512 tested in x265: how to enable it and does it help?](https://www.hwcooling.net/en/intel-avx-512-tested-in-x265-how-to-enable-it-and-does-it-help/)
6. [AVX Optimizations and Performance: VisualStudio vs GCC](https://community.intel.com/t5/Intel-ISA-Extensions/AVX-Optimizations-and-Performance-VisualStudio-vs-GCC/m-p/946717)

From what we understand, the performances improvement should range between 5 and 10%.

Hope that inspires !

**Comment by forart** [comment]
Bump.

Many a/v de/en-coders are introducing AVX optimizations, here's a couple of examples:
- @ultravideo's [ugv266 v0.8.0](https://github.com/ultravideo/uvg266/releases/tag/v0.8.0);
- [RareWares](https://www.rarewares.org/)'s [FLAC v1.4.3](https://www.rarewares.org/lossless.php#flac-bundle).

Last but not least, we've discovered this interesting (2019) article by @blegal and @cjego:
- [Low-latency and high-throughput software turbo decoders on multi-core architectures](https://www.researchgate.net/publication/334949536_Low-latency_and_high-throughput_software_turbo_decoders_on_multi-core_architectures)

Hope that helps.

**Comment by iEvgeny** [comment]
Low-level optimizations rely entirely on implementation in ffmpeg and are outside the purview of application software developers.
I'm currently busy implementing Zero Copy and I have to admit I'm stuck. The poor quality of graphics drivers for Linux and the specificity of the problem require more time. Progress is being made and I've already gotten the first results of reduced CPU and memory load, but I can't say anything about reduced playback latency yet.

**Comment by forart** [comment]
1st of all, thanks for reply.

> Low-level optimizations rely entirely on implementation in ffmpeg and are outside the purview of application software developers. 
>
Of course, but I believe that building binaries with AVX* compiler optimizations may help too.

> I'm currently busy implementing Zero Copy and I have to admit I'm stuck. The poor quality of graphics drivers for Linux and the specificity of the problem require more time. 
>
Dunno if can help/inspire in any way, but I've recently readed this article about (VirtIO) ZeroCopy:
https://www.phoronix.com/news/VirtIO-Vsock-MSG-Zerocopy

>Progress is being made and I've already gotten the first results of reduced CPU and memory load, but I can't say anything about reduced playback latency yet.
>
CCTV latency is more than acceptable for its primary use (monitoring surveillance cameras), but optimizing it could allow it to be used in more time-sensitive applications.

Last but not least, if you feel in a - temporary - deadlock state for ZC, it might be useful - even as a "recreation" - to focus on other features (such as [overlays](https://github.com/iEvgeny/cctv-viewer/issues/57)).

Thanks again for your (volunteer) work !

**Comment by iEvgeny** [comment]
CCTV Viewer does not operate on frame buffers directly. This is done by ffmpeg and partly by Qt.
As an experiment, you can rebuild ffmpeg and Qt on your machine locally with the desired optimizations. But I don't think it will have a noticeable effect.
