### ISSUE TITLE
always start cctv-viewer in full screen mode

### ISSUE THREAD

**Issue by B-KG** [iEvgeny/cctv-viewer#64]
Hi Evgeny, thanks for the great work developing this viewer. I need to make the viewer start in 'FULL SCREEN' always where should I make modification to the file/code?  Thanks.

**Comment by iEvgeny** [comment]
Hi!
Use `-f` parameter. More info `cctv-viewer --help-all`

**Comment by B-KG** [comment]
Evgeny, thanks for the quick reply that did the trick!
