### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by skyper-cz** [iEvgeny/cctv-viewer#68]
Hello
I wanted to use this software to view video from my DVR.
How do I do it?
Im running it on raspberry pi.

Have a nice day?

**Comment by iEvgeny** [comment]
Hi!
You need to get the stream addresses for your DVR. To do this, consult the "internet" or the manufacturer of your device.
Then the received addresses should be set in the settings for each CCTV Viewer viewport.

**Comment by skyper-cz** [comment]
I meant how is the command?

**Comment by skyper-cz** [comment]
Hi
I'm searching command that when I have IP for example http://1.2.3.4:80 that will support login and after will show the cameras at DVR.
