### ISSUE TITLE
Feature request:  CCTV feed playlist with timing on each camera

### ISSUE THREAD

**Issue by mabed-fr** [iEvgeny/cctv-viewer#70]
Hello,

thank you for your work the software is simple and efficient and in no case duplicates with other software

Is it possible to implement a playlist with pauses to be able to have each camera in full screen in succession with a specific timing ?

**Comment by iEvgeny** [comment]
Hi!
The latest release implements a carousel of presets. It is available through the settings. Configure the required cameras on each preset and set the required interval.

P.S.
Pausing scrolling by pressing the spacebar will be implemented soon.

**Comment by mabed-fr** [comment]
It’s great, it’s exactly what I want!
