### ISSUE TITLE
[Help request] Building on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by Hexality** [iEvgeny/cctv-viewer#73]
pattern_kde_qt5_devel installed, but still asking for something that it couldn't find. How do I fix this?

<pre><font color="#A6D189">❯</font> <font color="#8CAAEE">cmake</font><font color="#C6D0F5"> </font><font color="#A6D189">-G</font><font color="#C6D0F5"> </font><font color="#A6D189">&quot;Unix Makefiles&quot;</font><font color="#C6D0F5"> </font><font color="#A6D189">-DCMAKE_BUILD_TYPE=Release</font><font color="#C6D0F5"> </font><font color="#EEBEBE">..</font>
<font color="#E78284">CMake Error at CMakeLists.txt:79 (find_package):</font>
<font color="#E78284">  By not providing &quot;FindQt5QuickCompiler.cmake&quot; in CMAKE_MODULE_PATH this</font>
<font color="#E78284">  project has asked CMake to find a package configuration file provided by</font>
<font color="#E78284">  &quot;Qt5QuickCompiler&quot;, but CMake did not find one.</font>

<font color="#E78284">  Could not find a package configuration file provided by &quot;Qt5QuickCompiler&quot;</font>
<font color="#E78284">  with any of the following names:</font>

<font color="#E78284">    Qt5QuickCompilerConfig.cmake</font>
<font color="#E78284">    qt5quickcompiler-config.cmake</font>

<font color="#E78284">  Add the installation prefix of &quot;Qt5QuickCompiler&quot; to CMAKE_PREFIX_PATH or</font>
<font color="#E78284">  set &quot;Qt5QuickCompiler_DIR&quot; to a directory containing one of the above</font>
<font color="#E78284">  files.  If &quot;Qt5QuickCompiler&quot; provides a separate development package or</font>
<font color="#E78284">  SDK, be sure it has been installed.</font>

-- Configuring incomplete, errors occurred!
</pre>

**Comment by iEvgeny** [comment]
Try editing CMakeLists.txt.user following the advice in this answer https://stackoverflow.com/a/62063073
