### ISSUE TITLE
cant compile on arch linux

### ISSUE THREAD

**Issue by realdtn2** [iEvgeny/cctv-viewer#75]
[log.txt](https://github.com/iEvgeny/cctv-viewer/files/14229348/log.txt)

**Comment by realdtn2** [comment]
works now after reboot?

**Comment by iEvgeny** [comment]
For Arch Linux CCTV Viewer is available in Arch User Repository (AUR) https://aur.archlinux.org/packages/cctv-viewer-git
Please test the build from AUR.
