### ISSUE TITLE
[REQ] Hide Cursor

### ISSUE THREAD

**Issue by RUHavingFun** [iEvgeny/cctv-viewer#78]
command line option hide cursor

**Comment by RUHavingFun** [comment]
I have my Pi booting up and launching cctv-viewer automatically in a 2x2 setup full screen - but it seem the app overrides the OS and has it's own cursor that will not go away

**Comment by iEvgeny** [comment]
Implemented in the latest version.
The mouse cursor now automatically hides when the application is in full screen mode.
Please test it.

**Comment by RUHavingFun** [comment]
I am on 0.1.9.alpha via snap - it does seem the cursor goes away in full screen - thanks!
