### ISSUE TITLE
[snap] fails to start on wayland

### ISSUE THREAD

**Issue by verterok** [iEvgeny/cctv-viewer#8]
Hi,
Thanks for writing this, it's quite useful to integrate different video stream sources.
Tried to run the snap on wayland and it fails to start with the following error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```
Now running from a local built binary and it works fine, so the issue seems to be the snap itself.

Regards

**Comment by iEvgeny** [comment]
Hi!
As a temporary solution, please use my PPA: https://launchpad.net/~ievgeny/+archive/ubuntu/cctv-viewer
Working with Wayland confirmed at Kubunu 20.10. Subjectively, the performance is higher. In addition, the native package does not have some restrictions, unlike Snap. For example, the inability to resolve MDNS (Avahi) names.
I will continue working on Snap in the near future and ask you to test it with Wayland.

**Comment by verterok** [comment]
Hi,
Thanks for the ppa link.
Will keep the snap around and test it from time to time.
cheers,

**Comment by iEvgeny** [comment]
Fixed in the latest build. Please try it now.

**Comment by verterok** [comment]
confirmed, it works on wayland. 
Thanks!
