### ISSUE TITLE
Config not saved

### ISSUE THREAD

**Issue by martin-rizzi** [iEvgeny/cctv-viewer#88]
Hi! i'm having a problem with my cctv-viewer config. I've installed it on a debian PC and used a survilance monitor. the program start itself in kiosk mode via "snap run cctv-viewer -k" but lately it always restore factory config. that is a weird issue because the pc is not conected to the internet, it is on its own vlan and firewall secured to just get the camera streams. There is something i'm missing?

**Comment by iEvgeny** [comment]
Hi!
I don't think the problem is with CCTV Viewer. Check your snap installation.

**Comment by martin-rizzi** [comment]
reinstaled the program via snap and it worked fine. Thanks for support
