### ISSUE TITLE
[TECH] Does Linux 6.10 will improve cctv latencies ?

### ISSUE THREAD

**Issue by forart** [iEvgeny/cctv-viewer#89]
Hi there, I just read this interesting article and your software immediately came to mind:
> "Greatly improve send zerocopy performance, by enabling coalescing of sent buffers. MSG_ZEROCOPY already does this with send(2) and sendmsg(2), but the io_uring side did not. In local testing, the crossover point for send zerocopy being faster is now around 3000 byte packets, and it performs better than the sync syscall variants as well. This feature relies on a shared branch with net-next, which was pulled into both branches."

Source: https://www.phoronix.com/news/Linux-6.10-IO_uring

Do you think cctv will get latency benefits from it?

**Comment by iEvgeny** [comment]
Hi!
Although the terms are similar, this is information from a different area and may not be useful for reducing playback latency.

**Comment by forart** [comment]
Thanks for the explanation !
