### ISSUE TITLE
Crashes after a few hours on rasp 5 

### ISSUE THREAD

**Issue by DPattee** [iEvgeny/cctv-viewer#90]
Bought a Raspberry Pi 5 with 8 gigs of ram to drive a small display. Been testing it with just a few camera feeds for the past 2 days and cctv-viewer crashes after a few hours every run. 3 logs attached

$ dpkg --print-architecture
arm64
$ uname -a
Linux security-pi 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

[cctvlog-2.txt](https://github.com/iEvgeny/cctv-viewer/files/15472245/cctvlog-2.txt)
[cctvlog-3.txt](https://github.com/iEvgeny/cctv-viewer/files/15472246/cctvlog-3.txt)
[cctvlog.txt](https://github.com/iEvgeny/cctv-viewer/files/15472247/cctvlog.txt)

**Comment by iEvgeny** [comment]
Hi!
This is a known bug, fixes for which are already ready and will be published in the coming days.
I will also let you know when the fix is ​​ready for download.
Thanks for report!

**Comment by iEvgeny** [comment]
Have you had a chance to test the latest version?

**Comment by DPattee** [comment]
I've had it run for up to 7 hours without incident - double what it previously could do. 
Haven't had an opportunity to let it stay running longer than that yet, but I think we can consider this issue resolved at this point.
