### ISSUE TITLE
fit strem to view

### ISSUE THREAD

**Issue by RiKiM088** [iEvgeny/cctv-viewer#97]
hi, 1st thank you for such a useful app, fast and easy to use ! 

i have a dahua XVR with 4 cams, on the XVR itself and the XVR webpage the 4 cams are stretched to fit the views (1440x1620), but in CCTV-VIEWER even when the view is set to 16:9 the stream itself is narrowed in the middle with borders on the left and right.
I searched all over on the XVR side for any config, didn't find anything but maybe i am missing something
the url for the stream is "_rtsp://user:password@192.168.1.107:554/cam/realmonitor?channel=1&subtype=0_"

i know the issue maybe on the DAHUA side, so thank you for any info or help :)

**PS** : i checked issue #61, and is not the same problem as in my case the actual stream SHOULD fill the whole view.

**Comment by iEvgeny** [comment]
Hi!
In the last update I added support for FFmpeg `-aspect` option.
To convert a 4:3 frame to 16:9, try adding `-aspest 16:9` to the corresponding viewport settings field.

P.S.
Please make sure you have received the Snap update.
Due to technical issues on Canonical's side, the PPA version will be released later.

**Comment by RiKiM088** [comment]
I updated, and input the _-aspect 16:9_ in the FFmpeg options ! it worked Perfectly.

Thank you so much **iEvengy**, that was EXACTLY what i was looking for !!!

for normal surveillance situation CCTV-VIEWER is a much better/simpler/lighter option than the proprietary software of the XVR.

the only thing missing in my humble opinion is a mouse scroll controlled zoom function. hope to see that in next updates.

thanks again man

**Comment by iEvgeny** [comment]
Mouse wheel scrolling in plans.

**Comment by RiKiM088** [comment]
well then, thanks in advance ;)
