### ISSUE TITLE
Issues on viewing more than 3 streems

### ISSUE THREAD

**Issue by blackmlm** [iEvgeny/cctv-viewer#98]
Hi,

I’m having an issue with my Ubiquiti NVR, which streams camera feeds via RTSP. When I open CCTV-Viewer, only 3 of the 9 cameras load initially, while the rest just say "loading…" After a while, I might get another 3 to load, but the rest still don’t appear. If I restart CCTV-Viewer, sometimes different cameras will load, but it’s inconsistent.

Strangely, if I go to the settings and make any change in the FFmpeg settings (for example, adjusting a value from 0 to 10 or 10,000), the image appears immediately after I press enter. It seems like the stream only needs to retry to start working properly, but I'm unsure how to fix this.

Could you provide any advice? Thanks in advance.

**Comment by iEvgeny** [comment]
Hi!
Try increasing the `-analyzeduration` and  `-probesize` options to their default values.
It is also advisable to add the `-rtsp_transport tcp` option for RTSP streams.
The final set of FFmpeg options for RTSP stream may look like this: `-analyzeduration 5000000 -probesize 5000000 -rtsp_transport tcp`

**Comment by blackmlm** [comment]
Thanks.... you're the best

The -rtsp_transport tcp did the magic. 

Regards.
